[build]
  publish = "public"
  functions = "netlify/functions"
  command = "echo 'Static site and functions ready for deployment'"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
