[build]
      publish = "public"
      functions = "netlify/functions"
      command = "echo 'Static site and functions ready for deployment'" # Biarkan ini sederhana

    [[redirects]]
      from = "/.netlify/functions/*"
      to = "/.netlify/functions/:splat"
      status = 200
