[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install --prefix netlify/functions && echo 'Frontend build (if any) or static site is ready'"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
