[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  "*" = { timeout = 60 }

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
# Perubahan FINAL untuk memaksa deploy ulang yang bersih pada 30 Juli
